### ISSUE TITLE
Delete node onClose folder

### ISSUE THREAD

**Issue by maxime-gerum** [AngusFu/v-folder#2]
Hello AngusFu,

I work with large datas list and application seems to be slower if i open many folders.

I case of full ajax list, i want to modify code for delete node onClose folder, and reset to the default state for further ajax loads.

In index.vue, there is 

```
this.listen('unfold', node => {
        if (node.open && node.canOpen) {
          node.open =! node.open;
          return;
        }
```

I search a method for remove node : 

```
this.listen('unfold', node => {
        if (node.open && node.canOpen) {
          node.open =! node.open;

          // On close folder
          this.store.merge([], node)
          return;
        }
```

Something like this ? Thanks you

**Comment by AngusFu** [comment]
Yeah, there is performance problem when dealing with large data. I will improve this when I am free. You can remove nodes when folding a branch for now.

**Comment by maxime-gerum** [comment]
No problem, but my solution work strange, how i can remove node to the store ?

**Comment by AngusFu** [comment]
If you just want to delete nodes on folding a branch, just change those `v-show` directives into `v-if` in `v-branch.vue`. You don't need to empty the branch manually. 
But this might lead to performance issue when performing fold/unfold interactions with high frequency. (`v-if` vs `v-show`)

By the way, it can be tricky if you need to clean one branch and fetch it's data again. 
The problem is how to maintain those sub-branch and leafs's state unchanged with fresh data from server(especially when our branch's checked state is intermediate), because fresh data knows nothing about the previous state (if we must, it can be another challenge).

**Comment by maxime-gerum** [comment]
Hello AngusFu,

Thank you, i understand second way, and i change to v-if for the moment, but it's slowly too.

How delete properly branch with store if i don't want to keep sub-branch and leafs's states ?

**Comment by AngusFu** [comment]
You can add a `empty` method in `store.js`. Code below works, but it's not perfect because it doesn't handle it's ascendents' state, so it can look strange. We have to check all its ascendents to keep correct state as I did in the methods `checkNode` `checkLeaf`, and this might cause new performance issue.

```js
  empty(node) {
    let branch = this.findCurrentBranch(node.level);
    branch.node.open = false;
    branch.node.check = -1;
    branch.node.status = 'empty';
    branch.node.canOpen = false;
    branch.leafs = [];
    branch.branches = [];
  }
```

 This might work, but I'm not sure if it can do good for you. For this repo, we need to do a lot of things to improve performance. For instance, instead of keeping a reference to its parent, the key `level` is used to identify a node/leaf, I've no idea which is better, circular reference or just a level string?

**Comment by AngusFu** [comment]
This works:

```js
  empty(node) {
    let branch = this.findCurrentBranch(node.level);
    let parent = this.findParentBranch(node.level);
    branch.node.open = false;
    branch.node.check = -1;
    branch.node.status = 'empty';
    branch.node.canOpen = false;
    branch.leafs = [];
    branch.branches = [];
    this.checkBranchAscendents(this.findParentBranch(branch.level), -1);
  }
```

In `index.vue`, 

```js
node.open = !node.open;
this.store.empty(node); 
```

**Comment by AngusFu** [comment]
@Max25190  Please check the new branch `once`: https://github.com/v-comp/v-folder/tree/once

Hope it works —— with little confidence.

**Comment by maxime-gerum** [comment]
@AngusFu Thank you for your work, i think i have everything.

Regards.
